version: '3.8'
services:
  db:
    image: mysql:8.0.27
    container_name: 'sonho-meu-db'
    volumes:
      - ./.mysql:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=sonhomeu
      - MYSQL_DATABASE=sonhomeu
      - MYSQL_USER=sonhomeu
      - MYSQL_PASSWORD=sonhomeu
    ports:
      - 3307:3306
  wordpress:
    image: wordpress:latest
    container_name: 'sonho-meu-wp'
    volumes:
      - ./wp_data:/var/www/html
      - ./themes:/var/www/html/wp-content/themes
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=sonhomeu
      - WORDPRESS_DB_PASSWORD=sonhomeu
      - WORDPRESS_DB_NAME=sonhomeu